// Code generated by goctl. DO NOT EDIT.
// Source: publish.proto

package server

import (
	"context"

	"github.com/454270186/GoTikTok/rpc/publish/internal/logic"
	"github.com/454270186/GoTikTok/rpc/publish/internal/svc"
	"github.com/454270186/GoTikTok/rpc/publish/types/publish"
)

type PublishServer struct {
	svcCtx *svc.ServiceContext
	publish.UnimplementedPublishServer
}

func NewPublishServer(svcCtx *svc.ServiceContext) *PublishServer {
	return &PublishServer{
		svcCtx: svcCtx,
	}
}

func (s *PublishServer) PublishList(ctx context.Context, in *publish.PublishListReq) (*publish.PublishListRes, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}

func (s *PublishServer) PublishAction(ctx context.Context, in *publish.PublishActionReq) (*publish.PublishActionRes, error) {
	l := logic.NewPublishActionLogic(ctx, s.svcCtx)
	return l.PublishAction(in)
}
